# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Reuse Lint

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 2 * * 0"

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          _version=$(grep -o "reuse-.*" usbutils.spdx | cut -f2 -d'-')
          pip install reuse~=$_version

      - name: Check SPDX identifiers
        run: reuse lint
